import { describe, expect, it } from 'vitest';
import fc from 'fast-check';

import {
  classifyOutcome,
  type CallOutcomeKind,
  type SettledCall,
} from './callOutcome';

/**
 * Property test for the precedence the Profile_Call_Timeout holds over every
 * other signal of a settled call, placed beside the module it covers as the
 * design's Testing Strategy asks and running well above the 100-iteration
 * floor.
 *
 * This file carries **Property 3: A lapsed timeout wins over every status** —
 * for any settled call reporting that the Profile_Call_Timeout fired, the
 * outcome is `timeout` regardless of the status, the parse verdict, or their
 * absence (Requirement 12.4).
 *
 * Why the claim needs its own file rather than a line inside the totality
 * suite: a call can both lapse *and* settle. The Player_Stats_Api aborts at ten
 * seconds, and a response that was already in flight can arrive in the same
 * tick; whichever of the two the seam observes, Requirement 12.4 asks for the
 * call abandoned by our own limit to stay **distinguishable** from one
 * abandoned by the caller and from one whose transport rejected. In this module
 * that distinction is nothing more than the *order of two reads* — `timedOut`
 * before `status` — so the order is what is asserted here, from four angles:
 *
 *  1. **Dominance.** `timedOut` yields `timeout` for every status in 100–599
 *     walked exhaustively, for the absence of a status, for statuses no backend
 *     could send, and for both parse verdicts.
 *  2. **Inertness.** With the limit fired, the other two signals cannot change
 *     the answer at all: every settled call carrying `timedOut` classifies
 *     equal to every other, so the outcome is a function of that one field.
 *  3. **The status is never even read.** A `status` accessor that throws is
 *     offered, and the classification must still answer `timeout` — which no
 *     implementation reading the status first can do. This is the one assertion
 *     that can tell "checked first" from "checked, then overridden".
 *  4. **Non-vacuity.** The converse bounds the claim: with the limit unfired,
 *     *no* input yields `timeout`. Without this, a function answering `timeout`
 *     unconditionally would satisfy everything above.
 *
 * The three abandonment causes Requirement 12.4 names are then asserted side by
 * side, so a change collapsing our timer into the transport branch fails here
 * rather than silently in the screen.
 *
 * The exhaustive totality of the five-way classification is Property 1's claim
 * (`callOutcome.property.test.ts`), and the uniform concealment of `401`, `403`,
 * and `404` is Property 2's (`callOutcome.concealment.property.test.ts`); neither
 * is restated here beyond what the precedence needs.
 *
 * Requirements: 12.4
 */

// --- the expected outcome, written from the requirement ----------------------

/** The one outcome a lapsed limit may produce. */
const TIMEOUT_OUTCOME: CallOutcomeKind = { kind: 'timeout' };

// --- generators: the status signal -------------------------------------------

/** Every integer status a backend could send: 100 to 599 inclusive. */
const ALL_HTTP_STATUSES: readonly number[] = Array.from(
  { length: 500 },
  (_unused, offset) => 100 + offset,
);

/**
 * The statuses whose own branch is the strongest competitor to the timeout: a
 * `2xx` that would otherwise be a success or a parse failure, and the concealed
 * statuses that would otherwise be a not-found. A timeout losing its precedence
 * would most plausibly lose it to one of these — a response that beat the abort
 * by a tick — so they are generated by name as well as swept.
 */
const COMPETING_STATUSES: readonly number[] = [
  200, 201, 204, 299, 400, 401, 403, 404, 500, 503,
];

/** Any status a backend could send, drawn uniformly across 100–599. */
const httpStatusArb: fc.Arbitrary<number> = fc.constantFrom(
  ...ALL_HTTP_STATUSES,
);

/**
 * Statuses no backend sends, which a lapsed limit must still answer for rather
 * than raising: `0` and `-0` (a response claiming an impossible status),
 * negatives, fractions, both infinities, and `NaN`.
 */
const impossibleStatusArb: fc.Arbitrary<number> = fc.oneof(
  {
    weight: 5,
    arbitrary: fc.constantFrom(
      0,
      -0,
      -1,
      -404,
      1,
      99,
      600,
      1000,
      99_999,
      Number.NaN,
      Number.POSITIVE_INFINITY,
      Number.NEGATIVE_INFINITY,
      Number.MAX_SAFE_INTEGER,
      Number.MIN_SAFE_INTEGER,
      0.5,
      -0.5,
      200.5,
      404.000_001,
      599.5,
    ),
  },
  { weight: 2, arbitrary: fc.integer({ min: -1000, max: 99 }) },
  { weight: 2, arbitrary: fc.integer({ min: 600, max: 100_000 }) },
  { weight: 2, arbitrary: fc.double({ noNaN: true }) },
);

/**
 * Every status signal at once, the absence of a response included — `null` is
 * the signal a caller abort and a transport rejection both arrive as, and it is
 * exactly the one a timeout must stay distinguishable from.
 */
const anyStatusArb: fc.Arbitrary<number | null> = fc.oneof(
  { weight: 6, arbitrary: httpStatusArb },
  { weight: 4, arbitrary: fc.constantFrom(...COMPETING_STATUSES) },
  { weight: 3, arbitrary: fc.constant(null) },
  { weight: 3, arbitrary: impossibleStatusArb },
);

/** A settled call reporting that the Profile_Call_Timeout fired. */
const lapsedCallArb: fc.Arbitrary<SettledCall> = fc.record({
  status: anyStatusArb,
  timedOut: fc.constant(true),
  parsed: fc.boolean(),
});

/** A settled call of any shape at all, the limit included or not. */
const settledCallArb: fc.Arbitrary<SettledCall> = fc.record({
  status: anyStatusArb,
  timedOut: fc.boolean(),
  parsed: fc.boolean(),
});

// Feature: web-player-stats-screen, Property 3: A lapsed timeout wins over every status
// Validates: Requirements 12.4
describe('classifyOutcome — a lapsed timeout wins over every status', () => {
  it('yields timeout for any status, any parse verdict, and the absence of a status', () => {
    fc.assert(
      fc.property(lapsedCallArb, (call) => {
        // The property proper (12.4): our own limit fired, so the call is a
        // timeout whatever else arrived with it.
        expect(classifyOutcome(call)).toEqual(TIMEOUT_OUTCOME);
      }),
      { numRuns: 2000 },
    );
  });

  it('yields timeout for every integer status from 100 to 599 inclusive', () => {
    fc.assert(
      fc.property(fc.boolean(), (parsed) => {
        // The status space is walked in full rather than sampled, against a
        // generated parse verdict, so no status is left to chance — in
        // particular not the `2xx` a response winning the race would carry, nor
        // the `404` the endpoint conceals everything behind.
        for (const status of ALL_HTTP_STATUSES) {
          expect(classifyOutcome({ status, timedOut: true, parsed })).toEqual(
            TIMEOUT_OUTCOME,
          );
        }
      }),
      { numRuns: 150 },
    );
  });

  it('yields timeout carrying its kind and nothing else', () => {
    fc.assert(
      fc.property(lapsedCallArb, (call) => {
        // Requirements 3.7 and 12.5 are Property 4's claim, but the timeout arm
        // is asserted bare here too: a status that arrived after the limit has
        // no field to ride out on.
        const outcome = classifyOutcome(call);

        expect(outcome.kind).toBe('timeout');
        expect(Object.keys(outcome)).toEqual(['kind']);
      }),
      { numRuns: 500 },
    );
  });
});

// Feature: web-player-stats-screen, Property 3: A lapsed timeout wins over every status
// Validates: Requirements 12.4
describe('classifyOutcome — with the limit fired, the other signals are inert', () => {
  it('answers equally for any two lapsed calls, whatever their status and parse verdict', () => {
    fc.assert(
      fc.property(lapsedCallArb, lapsedCallArb, (first, second) => {
        // Stated as an equivalence rather than against a literal: with
        // `timedOut` set, the outcome is a function of that one field, so no
        // pair of lapsed calls can be told apart by their outcome (12.4).
        expect(classifyOutcome(first)).toEqual(classifyOutcome(second));
      }),
      { numRuns: 1000 },
    );
  });

  it('is unchanged by replacing the status of a lapsed call', () => {
    fc.assert(
      fc.property(anyStatusArb, anyStatusArb, fc.boolean(), (left, right, parsed) => {
        expect(classifyOutcome({ status: left, timedOut: true, parsed })).toEqual(
          classifyOutcome({ status: right, timedOut: true, parsed }),
        );
      }),
      { numRuns: 1000 },
    );
  });

  it('is unchanged by flipping the parse verdict of a lapsed call', () => {
    fc.assert(
      fc.property(anyStatusArb, (status) => {
        // A body the Response_Parser accepted does not rescue a call our own
        // limit already abandoned, and one it rejected does not rename it a
        // parse failure.
        expect(classifyOutcome({ status, timedOut: true, parsed: true })).toEqual(
          classifyOutcome({ status, timedOut: true, parsed: false }),
        );
      }),
      { numRuns: 1000 },
    );
  });

  it('never reads the status, so a throwing accessor is never touched', () => {
    fc.assert(
      fc.property(fc.boolean(), (parsed) => {
        // The one assertion that distinguishes "read first" from "read, then
        // overridden": an implementation consulting the status before the
        // timeout cannot pass this, however it ordered its branches afterwards.
        let reads = 0;
        const lapsedWithHostileStatus = {
          get status(): number {
            reads += 1;
            throw new Error('the status must never be read once the limit fired');
          },
          timedOut: true,
          parsed,
        } as unknown as SettledCall;

        expect(classifyOutcome(lapsedWithHostileStatus)).toEqual(TIMEOUT_OUTCOME);
        expect(reads).toBe(0);
      }),
      { numRuns: 200 },
    );
  });
});

// Feature: web-player-stats-screen, Property 3: A lapsed timeout wins over every status
// Validates: Requirements 12.4
describe('classifyOutcome — the claim is bounded, and the three abandonment causes stay apart', () => {
  it('yields timeout for no call whose limit did not fire', () => {
    fc.assert(
      fc.property(anyStatusArb, fc.boolean(), (status, parsed) => {
        // Non-vacuity: without this, a classification answering `timeout`
        // unconditionally would satisfy every property above. `timedOut` is the
        // only source of the timeout outcome, so a `504` from a gateway is a
        // transport failure and not a timeout of ours.
        expect(classifyOutcome({ status, timedOut: false, parsed }).kind).not.toBe(
          'timeout',
        );
      }),
      { numRuns: 1000 },
    );
  });

  it('separates our lapsed limit from a caller abort and from a rejected transport', () => {
    fc.assert(
      fc.property(fc.boolean(), (parsed) => {
        // 12.4 names three causes of an abandoned call where the screen shows
        // one Generic_Profile_Failure. The two inputs that reach this module —
        // our limit, and the absent response a caller abort and a transport
        // rejection both arrive as — are classified side by side so a collapse
        // of the pair fails here.
        const ourLimit = classifyOutcome({ status: null, timedOut: true, parsed });
        const noResponse = classifyOutcome({ status: null, timedOut: false, parsed });

        expect(ourLimit).toEqual(TIMEOUT_OUTCOME);
        expect(noResponse).toEqual({ kind: 'transport-failure' });
        expect(ourLimit.kind).not.toBe(noResponse.kind);
      }),
      { numRuns: 200 },
    );
  });

  it('is deterministic and leaves the settled call unmodified', () => {
    fc.assert(
      fc.property(settledCallArb, (call) => {
        const snapshot = { ...call };

        const first = classifyOutcome(call);
        const second = classifyOutcome(call);

        expect(first).toEqual(second);
        expect({ ...call }).toEqual(snapshot);
      }),
      { numRuns: 500 },
    );
  });
});
