import { describe, expect, it } from 'vitest';
import fc from 'fast-check';

import type { RatingSummary } from './parse/playerProfile';
import { resolveRatingCondition, type RatingCondition } from './ratingCondition';
import type { RatingState } from './wireEnums';
import {
  ratingSummaryArb,
  wireDisplayRatingArb,
  wireRatingStateArb,
} from '../testing/playerProfileFixtures';

/**
 * Property test for the precedence Never_Played holds over every other reading
 * of a rating block, placed beside the module it covers as the design's Testing
 * Strategy asks and running well above the 100-iteration floor.
 *
 * This file carries **Property 16: No appearances means never played, whatever
 * the rating says** — for any Rating_Summary at all, a zero Appearance_Count
 * resolves to `never-played` (Requirement 7.4).
 *
 * Why the claim needs its own file rather than a line inside the totality suite:
 * the glossary's Established_Rating and Never_Played definitions can **both**
 * hold of a single input. A membership created with a seeded skill tier carries
 * a rating block — a state, and a Display_Rating derived from it — before it has
 * played anything, so "established state *and* a present number *and* no
 * appearances" is not a contrived combination but the ordinary state of a newly
 * added player. Showing that person a figure is the precise confusion this
 * feature exists to remove (requirements.md → Context 3; `docs/backlog.md` →
 * Later / Ideas), and in `resolveRatingCondition` the whole of the protection is
 * the *order of two reads* — the count before the rating block. So the order is
 * what is asserted here, from four angles:
 *
 *  1. **Dominance.** Zero appearances yield `never-played` over every generated
 *     Rating_Summary, including each of the four shapes the Response_Parser can
 *     produce, and including the established-with-a-number combination the
 *     precedence exists to override, generated by name.
 *  2. **Inertness.** With no appearances, the rating block cannot change the
 *     answer at all: every such input classifies equal to every other, so the
 *     condition is a function of the count alone.
 *  3. **The rating block is never even read.** A block whose `state` and
 *     `displayRating` accessors throw must still resolve to `never-played` —
 *     which no implementation reading the rating first can do. This is the one
 *     assertion that distinguishes "checked first" from "checked, then
 *     overridden", and it is also what keeps the `established` arm from ever
 *     carrying a number out of a zero-appearance input.
 *  4. **Non-vacuity, in both directions.** The generator is asserted to really
 *     produce the established-with-a-number combination — without that, the
 *     dominance claim could be quantifying over inputs that never include the
 *     one case it is about — and the converse bounds the claim: with even one
 *     appearance, that same summary resolves to `established` carrying its
 *     number, so `never-played` is not being returned unconditionally.
 *
 * The totality and single-valuedness of the four-way resolution is Property 15's
 * claim (`ratingCondition.property.test.ts`) and is not restated here beyond
 * what the precedence needs; the rendered distinctness of the four labels is
 * Property 18's.
 *
 * Requirements: 7.4
 */

// --- the expected condition, written from the requirement --------------------

/** The one condition a zero Appearance_Count may produce. */
const NEVER_PLAYED: RatingCondition = { kind: 'never-played' };

// --- generators: the Appearance_Count ----------------------------------------

/**
 * The counts that mean the player has played nothing.
 *
 * Negative zero is included because it is `=== 0` and is the only sensible
 * reading of it: a count arriving as `-0` is still no appearances, and must not
 * fall through to the rating block.
 */
const noAppearancesArb: fc.Arbitrary<number> = fc.constantFrom(0, -0);

/** Counts that mean the player *has* played, for the converse. */
const someAppearancesArb: fc.Arbitrary<number> = fc.oneof(
  { weight: 3, arbitrary: fc.integer({ min: 1, max: 500 }) },
  {
    weight: 1,
    arbitrary: fc.constantFrom(1, 2, 1_000, Number.MAX_SAFE_INTEGER),
  },
);

// --- generators: the Rating_Summary ------------------------------------------

/** A Rating_State, present or absent, with an even spread over the three. */
const anyRatingStateArb: fc.Arbitrary<RatingState | null> = fc.oneof(
  { weight: 2, arbitrary: wireRatingStateArb },
  { weight: 1, arbitrary: fc.constant(null) },
);

/** A Display_Rating, present or absent. */
const anyDisplayRatingArb: fc.Arbitrary<number | null> = fc.oneof(
  { weight: 3, arbitrary: wireDisplayRatingArb },
  { weight: 1, arbitrary: fc.constant(null) },
);

/**
 * Every combination of the two members a Rating_Summary carries, declared here
 * rather than taken from the fixtures so the combination space is swept evenly —
 * the fixtures weight the four shapes the parser produces, which is the right
 * emphasis for a parse suite and the wrong one for a precedence sweep.
 */
const combinationSummaryArb: fc.Arbitrary<RatingSummary> = fc.record({
  state: anyRatingStateArb,
  displayRating: anyDisplayRatingArb,
});

/**
 * The combination the precedence exists to override: an established state
 * **and** a present Display_Rating — exactly what a seeded, never-played
 * membership looks like, and the one input that would otherwise render a figure.
 */
const establishedRatedSummaryArb: fc.Arbitrary<RatingSummary> = fc.record({
  state: fc.constant<RatingState>('Established'),
  displayRating: wireDisplayRatingArb,
});

/**
 * Any Rating_Summary at all: the four shapes the Response_Parser can produce
 * (via the shared fixtures, so a shape added there is a shape this suite reads),
 * the even combination sweep, and the override combination by name.
 */
const anySummaryArb: fc.Arbitrary<RatingSummary> = fc.oneof(
  { weight: 4, arbitrary: ratingSummaryArb },
  { weight: 4, arbitrary: combinationSummaryArb },
  { weight: 2, arbitrary: establishedRatedSummaryArb },
);

// Feature: web-player-stats-screen, Property 16: No appearances means never played, whatever the rating says
// Validates: Requirements 7.4
describe('resolveRatingCondition — no appearances means never played', () => {
  it('yields never-played for every rating summary', () => {
    fc.assert(
      fc.property(anySummaryArb, noAppearancesArb, (rating, appearances) => {
        // The property proper (7.4): nothing has been played, so nothing in the
        // rating block can produce a condition that asserts a rating.
        expect(resolveRatingCondition(rating, appearances)).toEqual(NEVER_PLAYED);
      }),
      { numRuns: 2000 },
    );
  });

  it('yields never-played for an established state carrying a display rating', () => {
    fc.assert(
      fc.property(
        establishedRatedSummaryArb,
        noAppearancesArb,
        (rating, appearances) => {
          // The combination the precedence is for, generated by name rather than
          // left to the sweep: a seeded membership that has played nothing still
          // reads as never-played, however settled its rating block looks.
          expect(resolveRatingCondition(rating, appearances)).toEqual(
            NEVER_PLAYED,
          );
        },
      ),
      { numRuns: 1000 },
    );
  });

  it('yields never-played for each of the four summary shapes the parser produces', () => {
    fc.assert(
      fc.property(ratingSummaryArb, noAppearancesArb, (rating, appearances) => {
        // Quantified over the shared fixtures, so the shapes this holds for are
        // exactly the shapes a parsed profile can carry.
        expect(resolveRatingCondition(rating, appearances)).toEqual(NEVER_PLAYED);
      }),
      { numRuns: 1000 },
    );
  });

  it('yields never-played carrying its kind and nothing else', () => {
    fc.assert(
      fc.property(anySummaryArb, noAppearancesArb, (rating, appearances) => {
        // The arm is asserted bare: a Display_Rating that was present in the
        // block has no field to ride out on, so no caller can reach for one
        // (Requirement 7.4 renders a label, not a figure).
        const condition = resolveRatingCondition(rating, appearances);

        expect(condition.kind).toBe('never-played');
        expect(Object.keys(condition)).toEqual(['kind']);
      }),
      { numRuns: 1000 },
    );
  });
});

// Feature: web-player-stats-screen, Property 16: No appearances means never played, whatever the rating says
// Validates: Requirements 7.4
describe('resolveRatingCondition — with no appearances, the rating block is inert', () => {
  it('answers equally for any two rating summaries read beside no appearances', () => {
    fc.assert(
      fc.property(
        anySummaryArb,
        anySummaryArb,
        noAppearancesArb,
        (first, second, appearances) => {
          // Stated as an equivalence rather than against a literal: with no
          // appearances the condition is a function of the count alone, so no
          // pair of rating blocks can be told apart by it.
          expect(resolveRatingCondition(first, appearances)).toEqual(
            resolveRatingCondition(second, appearances),
          );
        },
      ),
      { numRuns: 1000 },
    );
  });

  it('is unchanged by replacing the state of a zero-appearance summary', () => {
    fc.assert(
      fc.property(
        anyRatingStateArb,
        anyRatingStateArb,
        anyDisplayRatingArb,
        (left, right, displayRating) => {
          expect(
            resolveRatingCondition({ state: left, displayRating }, 0),
          ).toEqual(resolveRatingCondition({ state: right, displayRating }, 0));
        },
      ),
      { numRuns: 1000 },
    );
  });

  it('is unchanged by replacing the display rating of a zero-appearance summary', () => {
    fc.assert(
      fc.property(
        anyRatingStateArb,
        anyDisplayRatingArb,
        anyDisplayRatingArb,
        (state, left, right) => {
          // A number the backend sent does not rescue a membership that has
          // played nothing, and its absence does not rename the condition.
          expect(
            resolveRatingCondition({ state, displayRating: left }, 0),
          ).toEqual(resolveRatingCondition({ state, displayRating: right }, 0));
        },
      ),
      { numRuns: 1000 },
    );
  });

  it('never reads the rating block, so throwing accessors are never touched', () => {
    fc.assert(
      fc.property(noAppearancesArb, (appearances) => {
        // The one assertion that distinguishes "read first" from "read, then
        // overridden": an implementation consulting the rating block before the
        // count cannot pass this, however it ordered its branches afterwards.
        let reads = 0;
        const hostileSummary = {
          get state(): RatingState {
            reads += 1;
            throw new Error(
              'the rating state must never be read for a membership with no appearances',
            );
          },
          get displayRating(): number {
            reads += 1;
            throw new Error(
              'the display rating must never be read for a membership with no appearances',
            );
          },
        } as unknown as RatingSummary;

        expect(resolveRatingCondition(hostileSummary, appearances)).toEqual(
          NEVER_PLAYED,
        );
        expect(reads).toBe(0);
      }),
      { numRuns: 200 },
    );
  });
});

// Feature: web-player-stats-screen, Property 16: No appearances means never played, whatever the rating says
// Validates: Requirements 7.4
describe('resolveRatingCondition — the never-played claim is not vacuous', () => {
  it('generates the established-with-a-display-rating combination the precedence overrides', () => {
    // Non-vacuity of the quantification itself: the dominance claim above is
    // only about something if its generator actually reaches the combination in
    // which Established_Rating and Never_Played both hold. Sampled rather than
    // generated inside a property, because the claim is about the generator.
    const samples = fc.sample(anySummaryArb, 1000);

    const establishedAndRated = samples.filter(
      (summary) =>
        summary.state === 'Established' &&
        typeof summary.displayRating === 'number',
    );

    expect(establishedAndRated.length).toBeGreaterThan(0);

    // And the shapes the sweep is meant to cover are all reached, so no arm of
    // the combination space is silently missing.
    expect(
      samples.some((summary) => summary.state === 'Provisional'),
    ).toBe(true);
    expect(samples.some((summary) => summary.state === null)).toBe(true);
    expect(samples.some((summary) => summary.displayRating === null)).toBe(true);
  });

  it('resolves that same summary as established once there is one appearance', () => {
    fc.assert(
      fc.property(
        establishedRatedSummaryArb,
        someAppearancesArb,
        (rating, appearances) => {
          // The converse bounds the claim: without this, a resolver answering
          // `never-played` unconditionally would satisfy every property above.
          // The count is the only thing that changed, and the number comes
          // through exactly as parsed (Requirement 7.8).
          expect(resolveRatingCondition(rating, appearances)).toEqual({
            kind: 'established',
            displayRating: rating.displayRating,
          });
        },
      ),
      { numRuns: 1000 },
    );
  });

  it('yields never-played for no summary read beside at least one appearance', () => {
    fc.assert(
      fc.property(anySummaryArb, someAppearancesArb, (rating, appearances) => {
        // Zero is the sole source of the condition, so a player with one
        // appearance is never reported as having played none.
        expect(resolveRatingCondition(rating, appearances).kind).not.toBe(
          'never-played',
        );
      }),
      { numRuns: 1000 },
    );
  });

  it('is deterministic and leaves the rating summary unmodified', () => {
    fc.assert(
      fc.property(anySummaryArb, noAppearancesArb, (rating, appearances) => {
        const snapshot = { ...rating };

        const first = resolveRatingCondition(rating, appearances);
        const second = resolveRatingCondition(rating, appearances);

        expect(first).toEqual(second);
        expect({ ...rating }).toEqual(snapshot);
      }),
      { numRuns: 500 },
    );
  });
});
