import { describe, expect, it } from 'vitest';
import fc from 'fast-check';

import {
  INVITE_STATE_CODES,
  MEMBERSHIP_STATE_CODES,
  MEMBER_ROLE_CODES,
  REDEEM_OUTCOME_CODES,
  SQUAD_FEATURE_CODES,
  codeFromInviteState,
  codeFromMemberRole,
  codeFromMembershipState,
  codeFromRedeemOutcome,
  codeFromSquadFeature,
} from '../enumCodes';
import { isSquadIdentifier } from '../identifiers';
import {
  parseCreatedGuest,
  printCreatedGuest,
  type CreatedGuest,
} from './createdGuest';
import {
  parseCreatedSquad,
  printCreatedSquad,
  type CreatedSquad,
} from './createdSquad';
import {
  parseFeatureFlag,
  parseFeatureFlags,
  printFeatureFlag,
  printFeatureFlags,
  type FeatureFlag,
} from './featureFlags';
import {
  parseGeneratedInvite,
  printGeneratedInvite,
  type GeneratedInvite,
} from './generatedInvite';
import {
  parseInvitePreview,
  printInvitePreview,
  type InvitePreview,
} from './invitePreview';
import {
  parseInviteSummary,
  parseInviteSummaryList,
  printInviteSummary,
  printInviteSummaryList,
  type InviteSummary,
} from './inviteSummary';
import {
  parseDisplayRatingEntry,
  parseDisplayRatingLeaderboard,
  printDisplayRatingEntry,
  printDisplayRatingLeaderboard,
  type DisplayRatingEntry,
  type DisplayRatingLeaderboard,
} from './leaderboard';
import {
  MAX_INSTANT_MS,
  readInstantMs,
  type ParseResult,
} from './primitives';
import { parseRedemption, printRedemption, type Redemption } from './redemption';
import {
  parseSquadDetail,
  parseSquadMember,
  printSquadDetail,
  printSquadMember,
  type SquadDetail,
  type SquadMember,
} from './squadDetail';
import {
  parseSquadSummary,
  parseSquadSummaryList,
  printSquadSummary,
  printSquadSummaryList,
  type SquadSummary,
} from './squadSummary';

/**
 * Property test for the Response_Parser / Response_Printer pair, placed beside
 * the modules it covers as the design's Testing Strategy asks and running well
 * above the 100-iteration floor (20.1).
 *
 * This file carries **Property 36: Printing then parsing a value is the
 * identity** — for any producible parsed value of any of the feature's response
 * shapes, parsing that value's printed form yields a parsed outcome equal to the
 * original in every field, with enum values carried as their codes and instants
 * as the same instant on the time line (16.5, 20.2).
 *
 * Four things about how this is written matter more than the run counts.
 *
 * First, the round trip is stated **per shape, over all fifteen of them** — the
 * eleven body shapes plus the four element shapes their collections are built
 * from. One driver ({@link describeRoundTrip}) states the property once and is
 * invoked per shape, so a printer that forgot a field cannot hide behind a
 * sibling shape that round-trips.
 *
 * Second, only **producible** values are generated, because the property is about
 * values a parser can yield and no others. That constraint is read from the
 * modules rather than guessed:
 *
 *  - an identity is the 36-character hyphenated form `lib/identifiers.ts` accepts,
 *    in either letter case, and letter case is preserved because the identity is
 *    opaque to this feature;
 *  - an instant is a **whole millisecond** within `MAX_INSTANT_MS`, since
 *    `printInstant` deliberately prints anything else as a string the reader
 *    rejects rather than truncating it — a value that cannot round-trip must not
 *    appear to;
 *  - `redeemableLink` and `code` are non-empty, the bound `parseGeneratedInvite`
 *    states;
 *  - a leaderboard's entries carry **distinct** membership identities, because
 *    `parseDisplayRatingLeaderboard` fails a repeated one (8.11) — a generated
 *    duplicate would fail here for that reason rather than for a printer defect.
 *
 * A generator that drifted outside those bounds would report a printer defect
 * that is not there, so the last `describe` in the file asserts the generators'
 * own producibility directly.
 *
 * Third, **the comparison is over parsed values, and the wire form is checked
 * separately.** A parsed value holds an instant as epoch milliseconds and an enum
 * as its named value, so equality of parsed values compares instants as numbers
 * and enums as names — which is what makes the round trip exact rather than
 * spelling-sensitive: `'2026-01-01T00:00:00Z'` and `'2026-01-01T00:00:00.000+00:00'`
 * are the same instant. That the *wire* form carries the enum as its
 * Enum_Code_Map code and the instant as ISO-8601 with an explicit `Z` is a
 * separate claim, asserted against `codeFrom…` and `readInstantMs` in its own
 * section — without it, a pair that printed a name and parsed a name would
 * round-trip perfectly and still be wrong on the wire.
 *
 * Fourth, the shapes the task names explicitly are generated by name rather than
 * left to chance: `Redemption` in **both** the identity-bearing form and the
 * empty-body form the already-a-member no-op answers with, and leaderboards with
 * **0, 1, and 200** entries. Collections of 0, 1, and 200 are stated for the
 * member list and both response lists too, since a fold that mishandled an empty
 * or singleton collection is exactly the defect a mid-sized random array misses.
 *
 * Requirements: 16.5, 20.2
 */

/* -------------------------------------------------------------------------- */
/* Generators — producible values only                                        */
/* -------------------------------------------------------------------------- */

/** The hexadecimal digits an identity is spelled with, in both letter cases. */
const HEX_DIGITS = '0123456789abcdefABCDEF'.split('');

/** A run of `length` hexadecimal digits, mixed case. */
function hexRunArb(length: number): fc.Arbitrary<string> {
  return fc
    .array(fc.constantFrom(...HEX_DIGITS), { minLength: length, maxLength: length })
    .map((digits) => digits.join(''));
}

/**
 * An identity in the 36-character hyphenated form, in mixed, lower, and upper
 * case. Case is generated deliberately: the parser preserves it, so a printer
 * that normalised it would break the round trip on an upper-case identity alone.
 */
const identityArb: fc.Arbitrary<string> = fc.oneof(
  {
    weight: 4,
    arbitrary: fc
      .tuple(hexRunArb(8), hexRunArb(4), hexRunArb(4), hexRunArb(4), hexRunArb(12))
      .map((groups) => groups.join('-')),
  },
  { weight: 2, arbitrary: fc.uuid() },
  { weight: 1, arbitrary: fc.uuid().map((identity) => identity.toUpperCase()) },
);

/**
 * The name and display-name edges the design's Testing Strategy names: 0, 1, 100,
 * and 101 characters, whitespace-only, values equal to and near
 * `"Former player"`, and names differing only in case.
 */
const EDGE_TEXTS = [
  '',
  ' ',
  '   ',
  '\t',
  '\n',
  'a',
  'A',
  'Dave',
  'BigDave',
  'dave',
  'Former player',
  'former player',
  'Former Player',
  'Former player ',
  ' Former player',
  'Former playe',
  'A'.repeat(100),
  'A'.repeat(101),
  '🙂',
  '👨‍👩‍👧‍👦',
  'e\u0301',
  '\u00e9',
  '\u0000',
  'null',
  'undefined',
  'NaN',
  '__proto__',
  'constructor',
  'toString',
] as const;

/**
 * A free-form wire string. `readString` with no bounds accepts every string
 * exactly as supplied — nothing is trimmed and nothing is coerced — so every
 * string is producible, lone surrogates and control characters included.
 */
const wireTextArb: fc.Arbitrary<string> = fc.oneof(
  { weight: 5, arbitrary: fc.string({ maxLength: 40 }) },
  { weight: 2, arbitrary: fc.constantFrom(...EDGE_TEXTS) },
  { weight: 2, arbitrary: fc.string({ unit: 'grapheme', maxLength: 16 }) },
  { weight: 1, arbitrary: fc.string({ unit: 'binary', maxLength: 16 }) },
);

/**
 * A non-empty wire string, for the two secret-bearing fields of a
 * Generated_Invite: `parseGeneratedInvite` reads both with `{ minLength: 1 }`, so
 * the empty string is not a producible value there.
 */
const nonEmptyWireTextArb: fc.Arbitrary<string> = fc.oneof(
  { weight: 5, arbitrary: fc.string({ minLength: 1, maxLength: 64 }) },
  {
    weight: 3,
    arbitrary: fc.constantFrom(
      'a',
      ' ',
      'https://pitch-mate.co.uk/join/018f3a2b4c5d7e6f8a9b0c1d2e3f4a5b',
      'https://pitch-mate.co.uk/join/a%2Fb',
      'ABCD-1234',
      '🙂',
      'x'.repeat(512),
    ),
  },
  { weight: 2, arbitrary: fc.string({ unit: 'grapheme', minLength: 1, maxLength: 16 }) },
);

/**
 * Instants at the edges of what is printable: the epoch, the millisecond either
 * side of it, the year-0 and year-10000 boundaries where the printed form widens
 * to an expanded signed year, a leap day, sub-second precision, and both extremes
 * of the representable range.
 */
const EDGE_INSTANTS_MS = [
  0,
  1,
  -1,
  999,
  -999,
  1_000,
  1_700_000_000_123,
  1_767_225_600_000,
  1_709_164_800_000,
  -62_167_219_200_000,
  -62_167_219_200_001,
  253_402_300_799_999,
  253_402_300_800_000,
  MAX_INSTANT_MS,
  -MAX_INSTANT_MS,
  MAX_INSTANT_MS - 1,
  -MAX_INSTANT_MS + 1,
] as const;

/**
 * A producible instant: a whole millisecond within `MAX_INSTANT_MS`.
 *
 * The bound is not incidental. `printInstant` prints a fraction, an infinity, or
 * an out-of-range value as a string the reader **rejects**, precisely so a value
 * that cannot round-trip does not appear to — so those values are not producible
 * and are not generated here.
 *
 * **Negative zero is not a producible instant either.** `readInstantMs` yields
 * `localMs - offsetMinutes * 60_000`, and that subtraction produces positive zero
 * at the epoch, so no parse ever yields `-0`. It is worth stating because the
 * asymmetry is real and would otherwise look like a defect: `printInstant(-0)`
 * prints the epoch, which reads back as `+0`. Since a parser cannot produce `-0`
 * in an instant field, Property 36 says nothing about it — unlike a leaderboard
 * `value`, where `readNumber` accepts and preserves `-0` and the round trip
 * therefore must hold for it.
 */
const instantMsArb: fc.Arbitrary<number> = fc.oneof(
  // The four-digit-year range, where the great majority of real instants sit.
  {
    weight: 6,
    arbitrary: fc.integer({ min: -62_167_219_200_000, max: 253_402_300_799_999 }),
  },
  // The whole representable range, including the expanded-year regions.
  { weight: 3, arbitrary: fc.integer({ min: -MAX_INSTANT_MS, max: MAX_INSTANT_MS }) },
  { weight: 3, arbitrary: fc.constantFrom(...EDGE_INSTANTS_MS) },
);

/**
 * A producible leaderboard value: any finite number, since `readNumber` accepts
 * every finite number and the rounding to a displayed integer belongs to
 * `lib/ratingPresentation.ts` rather than to the parser (8.9).
 */
const leaderboardValueArb: fc.Arbitrary<number> = fc.oneof(
  { weight: 4, arbitrary: fc.integer({ min: -5_000, max: 5_000 }) },
  {
    weight: 3,
    arbitrary: fc
      .double({ noNaN: true, noDefaultInfinity: true })
      .filter(Number.isFinite),
  },
  {
    weight: 3,
    arbitrary: fc.constantFrom(
      0,
      -0,
      0.5,
      -0.5,
      1_000,
      1_499.5,
      -1_499.5,
      Number.EPSILON,
      Number.MIN_VALUE,
      -Number.MIN_VALUE,
      Number.MAX_VALUE,
      -Number.MAX_VALUE,
      Number.MAX_SAFE_INTEGER,
      Number.MIN_SAFE_INTEGER,
      2 ** 53,
      -(2 ** 53),
    ),
  },
);

/**
 * A record arbitrary whose values are ordinary objects.
 *
 * `fc.record` builds its values on a **null prototype**, while a parser builds
 * its result from an object literal. The two are equal field for field and
 * different in type, so `toStrictEqual` — which is right to separate them — would
 * report every round trip as a failure for a reason that has nothing to do with
 * the pair under test. Normalising here keeps the comparison strict about the
 * thing that matters (fields, and the absence of stray `undefined` ones) without
 * making it a test of how fast-check allocates.
 */
function plainRecord<T extends object>(arb: fc.Arbitrary<T>): fc.Arbitrary<T> {
  return arb.map((value) => ({ ...value }));
}

/**
 * The named values of each wire enum, read out of the Enum_Code_Map's own tables
 * rather than restated — this file must not carry a second declaration of the
 * names, and must not carry a numeric enum literal at all (16.12).
 */
const memberRoleArb = fc.constantFrom(...Object.values(MEMBER_ROLE_CODES));
const membershipStateArb = fc.constantFrom(...Object.values(MEMBERSHIP_STATE_CODES));
const squadFeatureArb = fc.constantFrom(...Object.values(SQUAD_FEATURE_CODES));
const inviteStateArb = fc.constantFrom(...Object.values(INVITE_STATE_CODES));
const redeemOutcomeArb = fc.constantFrom(...Object.values(REDEEM_OUTCOME_CODES));

/** A Squad_Summary; `role` and `state` are absences for a caller with no membership. */
const squadSummaryArb: fc.Arbitrary<SquadSummary> = plainRecord(
  fc.record({
    squadId: identityArb,
    name: wireTextArb,
    role: fc.option(memberRoleArb, { nil: null }),
    state: fc.option(membershipStateArb, { nil: null }),
  }),
);

/** A Squad_Member; `role` is an absence for a guest, `state` is always present. */
const squadMemberArb: fc.Arbitrary<SquadMember> = plainRecord(
  fc.record({
    membershipId: identityArb,
    displayName: wireTextArb,
    role: fc.option(memberRoleArb, { nil: null }),
    state: membershipStateArb,
    isGuest: fc.boolean(),
  }),
);

/** A Feature_Flag. A repeated feature is producible: the collection parser allows it. */
const featureFlagArb: fc.Arbitrary<FeatureFlag> = plainRecord(
  fc.record({
    feature: squadFeatureArb,
    isEnabled: fc.boolean(),
  }),
);

const featureFlagsArb: fc.Arbitrary<readonly FeatureFlag[]> = fc.array(featureFlagArb, {
  maxLength: 4,
});

/**
 * A Squad_Detail. Members may repeat a display name and even an identity — the
 * parser imposes no uniqueness there, unlike the leaderboard.
 */
const squadDetailArb: fc.Arbitrary<SquadDetail> = plainRecord(
  fc.record({
    squadId: identityArb,
    name: wireTextArb,
    members: fc.array(squadMemberArb, { maxLength: 8 }),
    features: featureFlagsArb,
  }),
);

/** An Invite_Summary; `createdBy` is a free-form actor string, `expiresAt` an absence. */
const inviteSummaryArb: fc.Arbitrary<InviteSummary> = plainRecord(
  fc.record({
    inviteId: identityArb,
    state: inviteStateArb,
    createdAtMs: instantMsArb,
    createdBy: fc.option(wireTextArb, { nil: null }),
    expiresAtMs: fc.option(instantMsArb, { nil: null }),
  }),
);

const generatedInviteArb: fc.Arbitrary<GeneratedInvite> = plainRecord(
  fc.record({
    inviteId: identityArb,
    redeemableLink: nonEmptyWireTextArb,
    code: nonEmptyWireTextArb,
    expiresAtMs: fc.option(instantMsArb, { nil: null }),
  }),
);

const invitePreviewArb: fc.Arbitrary<InvitePreview> = plainRecord(
  fc.record({
    requiresAuthentication: fc.boolean(),
    message: wireTextArb,
  }),
);

const createdSquadArb: fc.Arbitrary<CreatedSquad> = plainRecord(
  fc.record({
    squadId: identityArb,
    ownerMembershipId: identityArb,
  }),
);

const createdGuestArb: fc.Arbitrary<CreatedGuest> = plainRecord(
  fc.record({
    guestMembershipId: identityArb,
  }),
);

/** The identity-bearing Redemption form: a membership and a named outcome. */
const identityBearingRedemptionArb: fc.Arbitrary<Redemption> = plainRecord(
  fc.record({
    membershipId: identityArb,
    outcome: redeemOutcomeArb,
    squadId: fc.option(identityArb, { nil: null }),
  }),
);

/**
 * Every other producible Redemption: each of the three fields independently
 * present or absent, since each is read through `readOptional` in its own right.
 *
 * Built from a tuple rather than through {@link plainRecord}, because a record of
 * three optional readings widens to a type with *optional* properties, and a
 * Redemption's fields are present-and-nullable rather than optional — the parser
 * always yields all three.
 */
const mixedRedemptionArb: fc.Arbitrary<Redemption> = fc
  .tuple(
    fc.option(identityArb, { nil: null }),
    fc.option(redeemOutcomeArb, { nil: null }),
    fc.option(identityArb, { nil: null }),
  )
  .map(([membershipId, outcome, squadId]) => ({ membershipId, outcome, squadId }));

/**
 * Every producible Redemption, weighted so both forms the task names occur often:
 * the identity-bearing form, the all-absent value the empty body parses to, and
 * the mixed values the field-by-field optionality admits.
 */
const redemptionArb: fc.Arbitrary<Redemption> = fc.oneof(
  { weight: 4, arbitrary: identityBearingRedemptionArb },
  {
    weight: 2,
    arbitrary: fc.constant<Redemption>({
      membershipId: null,
      outcome: null,
      squadId: null,
    }),
  },
  { weight: 4, arbitrary: mixedRedemptionArb },
);

const displayRatingEntryArb: fc.Arbitrary<DisplayRatingEntry> = plainRecord(
  fc.record({
    membershipId: identityArb,
    displayName: wireTextArb,
    value: leaderboardValueArb,
  }),
);

/**
 * A leaderboard of `minLength`..`maxLength` entries carrying **distinct**
 * membership identities, because a repeated identity fails the parser (8.11) and
 * is therefore not a producible value.
 */
function leaderboardArb(
  minLength: number,
  maxLength: number,
): fc.Arbitrary<DisplayRatingLeaderboard> {
  return fc
    .uniqueArray(displayRatingEntryArb, {
      selector: (entry) => entry.membershipId,
      minLength,
      maxLength,
    })
    .map((entries) => ({ entries }));
}

/* -------------------------------------------------------------------------- */
/* Helpers                                                                    */
/* -------------------------------------------------------------------------- */

/**
 * The value of a reading that must have succeeded, raising with the reading's own
 * diagnostic reason when it did not.
 *
 * A reason is composed from literal labels only and never embeds the value that
 * was read, so surfacing it here cannot leak an Invite_Secret or a display name
 * into the test output (4.10, 17.2). fast-check reports the counterexample
 * separately.
 */
function mustParse<T>(parsed: ParseResult<T>): T {
  if (!parsed.ok) {
    throw new Error(`the printed form did not parse back: ${parsed.reason}`);
  }

  return parsed.value;
}

/** A printed wire form established as a plain object, for reading its properties. */
function wireObject(printed: unknown): Record<string, unknown> {
  expect(typeof printed).toBe('object');
  expect(printed).not.toBeNull();
  expect(Array.isArray(printed)).toBe(false);

  return printed as Record<string, unknown>;
}

/** A printed wire form established as an array. */
function wireArray(printed: unknown): readonly unknown[] {
  expect(Array.isArray(printed)).toBe(true);

  return printed as readonly unknown[];
}

/** The keys of a wire object, sorted, so a field set can be asserted whole. */
function wireKeys(printed: unknown): readonly string[] {
  return Object.keys(wireObject(printed)).sort();
}

/* -------------------------------------------------------------------------- */
/* The property, stated once and run per shape                                */
/* -------------------------------------------------------------------------- */

/**
 * Property 36 for one response shape.
 *
 * @param label the shape's name, for the test titles
 * @param arb producible values of the shape — see the module note on producibility
 * @param print the shape's Response_Printer
 * @param parse the shape's Response_Parser
 * @param numRuns iterations, at or above the 100-iteration floor (20.1)
 */
function describeRoundTrip<T>(
  label: string,
  arb: fc.Arbitrary<T>,
  print: (value: T) => unknown,
  parse: (body: unknown) => ParseResult<T>,
  numRuns = 300,
): void {
  // Feature: web-squads-screens, Property 36: Printing then parsing a value is the identity
  // Validates: Requirements 16.5, 20.2
  describe(`round trip — ${label}`, () => {
    it('parses its own printed form back to a value equal in every field', () => {
      fc.assert(
        fc.property(arb, (value) => {
          // The property proper (16.5): parse(print(v)) equals v. Instants compare
          // as epoch milliseconds and enums as named values, because that is what
          // a parsed value holds — the wire spelling is asserted separately.
          expect(mustParse(parse(print(value)))).toStrictEqual(value);
        }),
        { numRuns },
      );
    });

    it('reaches a fixed point, so a second round trip changes nothing', () => {
      fc.assert(
        fc.property(arb, (value) => {
          const once = mustParse(parse(print(value)));
          const twice = mustParse(parse(print(once)));

          // Identity once implies identity forever, but stating it catches a pair
          // that agreed on a *normalised* value rather than on the original: a
          // printer that dropped a field would settle on the second pass and pass
          // a weaker property that only compared consecutive rounds.
          expect(twice).toStrictEqual(once);
          expect(print(once)).toStrictEqual(print(value));
        }),
        { numRuns },
      );
    });

    it('prints a wire form determined by the value alone', () => {
      fc.assert(
        fc.property(arb, (value) => {
          // A printer is pure (16.10): no clock, no storage, no counter. Two
          // printings of one value must be indistinguishable, or the round trip
          // would hold only for whichever printing the parser happened to see.
          expect(print(value)).toStrictEqual(print(value));
        }),
        { numRuns },
      );
    });
  });
}

describeRoundTrip<SquadSummary>(
  'Squad_Summary',
  squadSummaryArb,
  printSquadSummary,
  parseSquadSummary,
);

describeRoundTrip<readonly SquadSummary[]>(
  'the ListMySquads body',
  fc.array(squadSummaryArb, { maxLength: 8 }),
  printSquadSummaryList,
  parseSquadSummaryList,
);

describeRoundTrip<SquadMember>(
  'Squad_Member',
  squadMemberArb,
  printSquadMember,
  parseSquadMember,
);

describeRoundTrip<SquadDetail>(
  'the GetSquad body',
  squadDetailArb,
  printSquadDetail,
  parseSquadDetail,
);

describeRoundTrip<FeatureFlag>(
  'Feature_Flag',
  featureFlagArb,
  printFeatureFlag,
  parseFeatureFlag,
);

describeRoundTrip<readonly FeatureFlag[]>(
  'the GetFeatureFlags body',
  featureFlagsArb,
  printFeatureFlags,
  parseFeatureFlags,
);

describeRoundTrip<InviteSummary>(
  'Invite_Summary',
  inviteSummaryArb,
  printInviteSummary,
  parseInviteSummary,
);

describeRoundTrip<readonly InviteSummary[]>(
  'the ListInvites body',
  fc.array(inviteSummaryArb, { maxLength: 8 }),
  printInviteSummaryList,
  parseInviteSummaryList,
);

describeRoundTrip<GeneratedInvite>(
  'Generated_Invite',
  generatedInviteArb,
  printGeneratedInvite,
  parseGeneratedInvite,
);

describeRoundTrip<InvitePreview>(
  'Invite_Preview',
  invitePreviewArb,
  printInvitePreview,
  parseInvitePreview,
);

describeRoundTrip<CreatedSquad>(
  'Created_Squad',
  createdSquadArb,
  printCreatedSquad,
  parseCreatedSquad,
);

describeRoundTrip<CreatedGuest>(
  'Created_Guest',
  createdGuestArb,
  printCreatedGuest,
  parseCreatedGuest,
);

describeRoundTrip<Redemption>(
  'Redemption, both wire forms',
  redemptionArb,
  printRedemption,
  parseRedemption,
);

describeRoundTrip<DisplayRatingEntry>(
  'a Display_Rating entry',
  displayRatingEntryArb,
  printDisplayRatingEntry,
  parseDisplayRatingEntry,
);

describeRoundTrip<DisplayRatingLeaderboard>(
  'the GetSquadLeaderboard body',
  leaderboardArb(0, 12),
  printDisplayRatingLeaderboard,
  parseDisplayRatingLeaderboard,
);

/* -------------------------------------------------------------------------- */
/* The wire form: enums as codes, instants as ISO-8601 with an explicit Z      */
/* -------------------------------------------------------------------------- */

/**
 * The round trip above compares *parsed* values, which is what makes it exact.
 * That leaves one thing unstated, and it is the thing that would matter on a real
 * wire: a pair that printed a name and parsed a name back would satisfy the
 * identity and still be wrong. So the printed form is checked against the
 * Enum_Code_Map's own reverse readers and against `readInstantMs`, and each
 * shape's field set is asserted whole so a printer cannot emit a property its
 * parser never reads.
 */
// Feature: web-squads-screens, Property 36: Printing then parsing a value is the identity
// Validates: Requirements 16.5, 20.2
describe('round trip — the wire form carries enums as codes and instants as instants', () => {
  it('prints a Squad_Summary as four properties, each enum as its code', () => {
    fc.assert(
      fc.property(squadSummaryArb, (summary) => {
        const wire = wireObject(printSquadSummary(summary));

        expect(wireKeys(wire)).toStrictEqual(['name', 'role', 'squadId', 'state']);
        expect(wire.squadId).toBe(summary.squadId);
        expect(wire.name).toBe(summary.name);
        expect(wire.role).toBe(
          summary.role === null ? null : codeFromMemberRole(summary.role),
        );
        expect(wire.state).toBe(
          summary.state === null ? null : codeFromMembershipState(summary.state),
        );
      }),
      { numRuns: 300 },
    );
  });

  it('prints a Squad_Member with its state as a code and its guest flag as a boolean', () => {
    fc.assert(
      fc.property(squadMemberArb, (member) => {
        const wire = wireObject(printSquadMember(member));

        expect(wireKeys(wire)).toStrictEqual([
          'displayName',
          'isGuest',
          'membershipId',
          'role',
          'state',
        ]);
        expect(wire.membershipId).toBe(member.membershipId);
        expect(wire.displayName).toBe(member.displayName);
        expect(wire.role).toBe(
          member.role === null ? null : codeFromMemberRole(member.role),
        );
        // Required rather than nullable here: a membership always has a state.
        expect(wire.state).toBe(codeFromMembershipState(member.state));
        expect(wire.isGuest).toBe(member.isGuest);
      }),
      { numRuns: 300 },
    );
  });

  it('prints a Feature_Flag as its feature code and state', () => {
    fc.assert(
      fc.property(featureFlagArb, (flag) => {
        const wire = wireObject(printFeatureFlag(flag));

        expect(wireKeys(wire)).toStrictEqual(['feature', 'isEnabled']);
        expect(wire.feature).toBe(codeFromSquadFeature(flag.feature));
        expect(wire.isEnabled).toBe(flag.isEnabled);
      }),
      { numRuns: 200 },
    );
  });

  it('prints an Invite_Summary state as a code and both instants as ISO-8601 with a Z', () => {
    fc.assert(
      fc.property(inviteSummaryArb, (summary) => {
        const wire = wireObject(printInviteSummary(summary));

        expect(wireKeys(wire)).toStrictEqual([
          'createdAt',
          'createdBy',
          'expiresAt',
          'inviteId',
          'state',
        ]);
        expect(wire.state).toBe(codeFromInviteState(summary.state));
        // The same instant on the time line, not the same string: the reader is
        // what decides, so it is the reader that is asked.
        expect(typeof wire.createdAt).toBe('string');
        expect(String(wire.createdAt).endsWith('Z')).toBe(true);
        expect(mustParse(readInstantMs(wire.createdAt, 'createdAt'))).toBe(
          summary.createdAtMs,
        );

        if (summary.expiresAtMs === null) {
          expect(wire.expiresAt).toBeNull();
        } else {
          expect(String(wire.expiresAt).endsWith('Z')).toBe(true);
          expect(mustParse(readInstantMs(wire.expiresAt, 'expiresAt'))).toBe(
            summary.expiresAtMs,
          );
        }

        // A free-form actor string, printed as it stands — not an identity.
        expect(wire.createdBy).toBe(summary.createdBy);
      }),
      { numRuns: 400 },
    );
  });

  it('prints a Generated_Invite expiry as ISO-8601 with a Z, or as an absence', () => {
    fc.assert(
      fc.property(generatedInviteArb, (invite) => {
        const wire = wireObject(printGeneratedInvite(invite));

        expect(wireKeys(wire)).toStrictEqual([
          'code',
          'expiresAt',
          'inviteId',
          'redeemableLink',
        ]);
        // Both secret-bearing fields survive verbatim: this body carries the
        // Invite_Secret exactly once, so a printer that altered it would be
        // altering a value nothing can re-read.
        expect(wire.redeemableLink).toBe(invite.redeemableLink);
        expect(wire.code).toBe(invite.code);

        if (invite.expiresAtMs === null) {
          expect(wire.expiresAt).toBeNull();
        } else {
          expect(String(wire.expiresAt).endsWith('Z')).toBe(true);
          expect(mustParse(readInstantMs(wire.expiresAt, 'expiresAt'))).toBe(
            invite.expiresAtMs,
          );
        }
      }),
      { numRuns: 300 },
    );
  });

  it('prints a Redemption as three nullable properties in both forms', () => {
    fc.assert(
      fc.property(redemptionArb, (redemption) => {
        const wire = wireObject(printRedemption(redemption));

        // The no-op form prints as three nulls rather than as an absent body, so
        // that one code path serves both wire forms and the round trip stays exact.
        expect(wireKeys(wire)).toStrictEqual(['membershipId', 'outcome', 'squadId']);
        expect(wire.membershipId).toBe(redemption.membershipId);
        expect(wire.squadId).toBe(redemption.squadId);
        expect(wire.outcome).toBe(
          redemption.outcome === null
            ? null
            : codeFromRedeemOutcome(redemption.outcome),
        );
      }),
      { numRuns: 300 },
    );
  });

  it('prints a leaderboard as its entries alone, carrying no statistic', () => {
    fc.assert(
      fc.property(leaderboardArb(0, 8), (leaderboard) => {
        const wire = wireObject(printDisplayRatingLeaderboard(leaderboard));

        // `statistic` is not read and so is not printed: the caller already knows
        // which statistic it asked for, and emitting the code would put a numeric
        // enum literal outside the Enum_Code_Map (16.12).
        expect(wireKeys(wire)).toStrictEqual(['entries']);
        expect(wireArray(wire.entries)).toHaveLength(leaderboard.entries.length);

        wireArray(wire.entries).forEach((printedEntry, index) => {
          const entry = leaderboard.entries[index];
          const entryWire = wireObject(printedEntry);

          expect(wireKeys(entryWire)).toStrictEqual([
            'displayName',
            'membershipId',
            'value',
          ]);
          expect(entryWire.membershipId).toBe(entry.membershipId);
          expect(entryWire.displayName).toBe(entry.displayName);
          // The value is printed as the number it is: no rounding, no scaling.
          expect(entryWire.value).toBe(entry.value);
        });
      }),
      { numRuns: 300 },
    );
  });

  it('prints a Squad_Detail with its members and features in order', () => {
    fc.assert(
      fc.property(squadDetailArb, (detail) => {
        const wire = wireObject(printSquadDetail(detail));

        expect(wireKeys(wire)).toStrictEqual([
          'features',
          'members',
          'name',
          'squadId',
        ]);
        // Order is part of the value: the Player_Order sorts the parsed members,
        // so a printer that reordered them would make the round trip inexact in a
        // way only a sorted comparison would hide.
        expect(wireArray(wire.members)).toStrictEqual(
          detail.members.map(printSquadMember),
        );
        expect(wireArray(wire.features)).toStrictEqual(
          detail.features.map(printFeatureFlag),
        );
      }),
      { numRuns: 300 },
    );
  });

  it('prints an Invite_Preview as exactly the two properties its parser reads', () => {
    fc.assert(
      fc.property(invitePreviewArb, (preview) => {
        const wire = wireObject(printInvitePreview(preview));

        // Nothing else: this is the one anonymous call, and its body must disclose
        // nothing about whether a squad exists.
        expect(wireKeys(wire)).toStrictEqual(['message', 'requiresAuthentication']);
        expect(wire.requiresAuthentication).toBe(preview.requiresAuthentication);
        expect(wire.message).toBe(preview.message);
      }),
      { numRuns: 200 },
    );
  });

  it('prints the two identity-only bodies as their identities', () => {
    fc.assert(
      fc.property(createdSquadArb, createdGuestArb, (created, guest) => {
        const squadWire = wireObject(printCreatedSquad(created));
        const guestWire = wireObject(printCreatedGuest(guest));

        expect(wireKeys(squadWire)).toStrictEqual(['ownerMembershipId', 'squadId']);
        expect(squadWire.squadId).toBe(created.squadId);
        expect(squadWire.ownerMembershipId).toBe(created.ownerMembershipId);

        expect(wireKeys(guestWire)).toStrictEqual(['guestMembershipId']);
        expect(guestWire.guestMembershipId).toBe(guest.guestMembershipId);
      }),
      { numRuns: 200 },
    );
  });
});

/* -------------------------------------------------------------------------- */
/* Redemption: both wire forms, including the empty body                      */
/* -------------------------------------------------------------------------- */

/**
 * `RedeemInvite` is the one operation with two valid wire forms, and the round
 * trip has to hold for both. The identity-bearing form is covered by the driver
 * above; the empty body needs stating, because its *input* is an absence while
 * its printed form is an object — so "print then parse" and "parse then print
 * then parse" are different journeys and both must land on the same value.
 */
// Feature: web-squads-screens, Property 36: Printing then parsing a value is the identity
// Validates: Requirements 16.5, 20.2
describe('round trip — Redemption in the identity-bearing and empty-body forms', () => {
  it('parses the empty body to three absences, whether absent or null', () => {
    const fromAbsent = mustParse(parseRedemption(undefined));
    const fromNull = mustParse(parseRedemption(null));

    expect(fromAbsent).toStrictEqual({
      membershipId: null,
      outcome: null,
      squadId: null,
    });
    expect(fromNull).toStrictEqual(fromAbsent);
  });

  it('round-trips the value the empty body parses to', () => {
    fc.assert(
      // A constant, run under `fc.assert` so this sits inside the property rather
      // than beside it: the empty-body form is one of the values Property 36
      // quantifies over, not a separate example.
      fc.property(fc.constantFrom(undefined, null), (emptyBody) => {
        const parsed = mustParse(parseRedemption(emptyBody));
        const reparsed = mustParse(parseRedemption(printRedemption(parsed)));

        // Failing the empty body would turn "you are already in this squad" into
        // the Generic_Squads_Failure, so this is the round trip that keeps the
        // no-op a success.
        expect(reparsed).toStrictEqual(parsed);
      }),
      { numRuns: 100 },
    );
  });

  it('round-trips the identity-bearing form with both fields present', () => {
    fc.assert(
      fc.property(identityBearingRedemptionArb, (redemption) => {
        expect(mustParse(parseRedemption(printRedemption(redemption)))).toStrictEqual(
          redemption,
        );
      }),
      { numRuns: 300 },
    );
  });

  it('keeps the two forms distinguishable through the round trip', () => {
    fc.assert(
      fc.property(identityBearingRedemptionArb, (redemption) => {
        const empty = mustParse(parseRedemption(undefined));
        const bearing = mustParse(parseRedemption(printRedemption(redemption)));

        // The round trip must not collapse a redemption that joined a squad into
        // the no-op value: the Squads_Home's direct-navigation branch reads these
        // fields to decide where to go next (4.6, 5.8).
        expect(bearing).not.toStrictEqual(empty);
        expect(bearing.membershipId).toBe(redemption.membershipId);
        expect(bearing.outcome).toBe(redemption.outcome);
      }),
      { numRuns: 300 },
    );
  });
});

/* -------------------------------------------------------------------------- */
/* Collections at 0, 1, and 200                                               */
/* -------------------------------------------------------------------------- */

/**
 * The sizes the task names, stated for each collection the feature parses. A
 * mid-sized random array exercises the general fold; 0 and 1 are where an
 * off-by-one or an empty-case special path would show, and 200 is where a
 * quadratic duplicate check or a recursive fold would.
 */
// Feature: web-squads-screens, Property 36: Printing then parsing a value is the identity
// Validates: Requirements 16.5, 20.2
describe('round trip — collections of 0, 1, and 200 entries', () => {
  const sizes = [0, 1, 200] as const;

  for (const size of sizes) {
    it(`round-trips a leaderboard of ${size} entries with distinct identities`, () => {
      fc.assert(
        fc.property(leaderboardArb(size, size), (leaderboard) => {
          expect(leaderboard.entries).toHaveLength(size);
          expect(
            mustParse(
              parseDisplayRatingLeaderboard(
                printDisplayRatingLeaderboard(leaderboard),
              ),
            ),
          ).toStrictEqual(leaderboard);
        }),
        { numRuns: 100 },
      );
    });

    it(`round-trips a squad of ${size} members`, () => {
      fc.assert(
        fc.property(
          plainRecord(
            fc.record({
              squadId: identityArb,
              name: wireTextArb,
              members: fc.array(squadMemberArb, { minLength: size, maxLength: size }),
              features: featureFlagsArb,
            }),
          ),
          (detail: SquadDetail) => {
            expect(detail.members).toHaveLength(size);
            expect(
              mustParse(parseSquadDetail(printSquadDetail(detail))),
            ).toStrictEqual(detail);
          },
        ),
        { numRuns: 100 },
      );
    });

    it(`round-trips a squads listing of ${size} summaries`, () => {
      fc.assert(
        fc.property(
          fc.array(squadSummaryArb, { minLength: size, maxLength: size }),
          (summaries) => {
            expect(
              mustParse(parseSquadSummaryList(printSquadSummaryList(summaries))),
            ).toStrictEqual(summaries);
          },
        ),
        { numRuns: 100 },
      );
    });

    it(`round-trips an invite listing of ${size} summaries`, () => {
      fc.assert(
        fc.property(
          fc.array(inviteSummaryArb, { minLength: size, maxLength: size }),
          (summaries) => {
            expect(
              mustParse(parseInviteSummaryList(printInviteSummaryList(summaries))),
            ).toStrictEqual(summaries);
          },
        ),
        { numRuns: 100 },
      );
    });
  }
});

/* -------------------------------------------------------------------------- */
/* The generators are themselves producible                                   */
/* -------------------------------------------------------------------------- */

/**
 * Property 36 is a claim about *producible* values, so a generator that strayed
 * outside what a parser can yield would report a printer defect that is not
 * there — a fractional instant, an unhyphenated identity, or a leaderboard with a
 * repeated membership would each fail the round trip for a reason the printer is
 * not responsible for. These assertions pin the generators to the bounds the
 * modules state, so a failure above is a failure of the pair rather than of this
 * file.
 */
// Feature: web-squads-screens, Property 36: Printing then parsing a value is the identity
// Validates: Requirements 16.5, 20.2
describe('round trip — the generators produce only producible values', () => {
  it('generates identities in the 36-character hyphenated form', () => {
    fc.assert(
      fc.property(identityArb, (identity) => {
        expect(isSquadIdentifier(identity)).toBe(true);
      }),
      { numRuns: 500 },
    );
  });

  it('generates instants as whole milliseconds within the representable range', () => {
    fc.assert(
      fc.property(instantMsArb, (instantMs) => {
        // Exactly the bound `printInstant` enforces. Outside it the printer emits
        // a string the reader rejects, deliberately, so such values are not
        // producible and must not be generated.
        expect(Number.isInteger(instantMs)).toBe(true);
        expect(Math.abs(instantMs)).toBeLessThanOrEqual(MAX_INSTANT_MS);
        // And never negative zero, which no parse yields — see the note on
        // `instantMsArb`.
        expect(Object.is(instantMs, -0)).toBe(false);
      }),
      { numRuns: 500 },
    );
  });

  it('generates leaderboard values including negative zero, which a parse does yield', () => {
    // The counterpart of the rule above, stated so the two are not confused: a
    // `value` of `-0` is read and preserved by `readNumber`, so it is producible
    // and the round trip is asserted over it.
    expect(mustParse(readInstantMs('1970-01-01T00:00:00.000Z', 'epoch'))).toBe(0);
    expect(
      mustParse(
        parseDisplayRatingEntry(
          printDisplayRatingEntry({
            membershipId: '00000000-0000-7000-8000-000000000000',
            displayName: 'Dave',
            value: -0,
          }),
        ),
      ).value,
    ).toBe(-0);
  });

  it('generates leaderboard values that are finite numbers', () => {
    fc.assert(
      fc.property(leaderboardValueArb, (value) => {
        expect(Number.isFinite(value)).toBe(true);
      }),
      { numRuns: 500 },
    );
  });

  it('generates leaderboards whose membership identities are distinct', () => {
    fc.assert(
      fc.property(leaderboardArb(0, 12), (leaderboard) => {
        const identities = leaderboard.entries.map((entry) => entry.membershipId);

        // The one uniqueness rule in the parsers (8.11). Identities compare
        // exactly, so two differing only in case are distinct here as they are
        // there.
        expect(new Set(identities).size).toBe(identities.length);
      }),
      { numRuns: 300 },
    );
  });

  it('generates non-empty secret-bearing strings for a Generated_Invite', () => {
    fc.assert(
      fc.property(nonEmptyWireTextArb, (text) => {
        expect(text.length).toBeGreaterThanOrEqual(1);
      }),
      { numRuns: 300 },
    );
  });

  it('generates only named enum values, drawn from the Enum_Code_Map tables', () => {
    fc.assert(
      fc.property(
        memberRoleArb,
        membershipStateArb,
        squadFeatureArb,
        inviteStateArb,
        redeemOutcomeArb,
        (role, state, feature, inviteState, outcome) => {
          // Each must map to a code, since an unnamed value has none and could
          // never have been parsed in the first place.
          expect(Number.isInteger(codeFromMemberRole(role))).toBe(true);
          expect(Number.isInteger(codeFromMembershipState(state))).toBe(true);
          expect(Number.isInteger(codeFromSquadFeature(feature))).toBe(true);
          expect(Number.isInteger(codeFromInviteState(inviteState))).toBe(true);
          expect(Number.isInteger(codeFromRedeemOutcome(outcome))).toBe(true);
        },
      ),
      { numRuns: 300 },
    );
  });
});
