// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PitchMate.Infrastructure.Data;

#nullable disable

namespace PitchMate.Infrastructure.Migrations
{
    [DbContext(typeof(PitchMateDbContext))]
    [Migration("20260114165319_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PitchMate.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<Guid>("SquadId")
                        .HasColumnType("uuid")
                        .HasColumnName("squad_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TeamSize")
                        .HasColumnType("integer")
                        .HasColumnName("team_size");

                    b.HasKey("Id");

                    b.HasIndex("SquadId");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("PitchMate.Domain.Entities.Squad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("squads", (string)null);
                });

            modelBuilder.Entity("PitchMate.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_id");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("google_id IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("squad_admins", b =>
                {
                    b.Property<Guid>("squad_id")
                        .HasColumnType("uuid")
                        .HasColumnName("squad_id");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("squad_id", "user_id");

                    b.ToTable("squad_admins", (string)null);
                });

            modelBuilder.Entity("PitchMate.Domain.Entities.Match", b =>
                {
                    b.HasOne("PitchMate.Domain.Entities.Squad", null)
                        .WithMany()
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("PitchMate.Domain.ValueObjects.MatchPlayer", "Players", b1 =>
                        {
                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uuid")
                                .HasColumnName("match_id");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<int>("RatingAtMatchTime")
                                .HasColumnType("integer")
                                .HasColumnName("rating_at_match_time");

                            b1.Property<string>("TeamDesignation")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("team_designation");

                            b1.HasKey("MatchId", "UserId");

                            b1.HasIndex("UserId");

                            b1.ToTable("match_players", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MatchId");

                            b1.HasOne("PitchMate.Domain.Entities.User", null)
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    b.OwnsOne("PitchMate.Domain.ValueObjects.MatchResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uuid")
                                .HasColumnName("match_id");

                            b1.Property<string>("BalanceFeedback")
                                .HasColumnType("text")
                                .HasColumnName("balance_feedback");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<string>("Winner")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("winner");

                            b1.HasKey("MatchId");

                            b1.ToTable("match_results", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.Navigation("Players");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("PitchMate.Domain.Entities.User", b =>
                {
                    b.OwnsMany("PitchMate.Domain.ValueObjects.SquadMembership", "SquadMemberships", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<Guid>("SquadId")
                                .HasColumnType("uuid")
                                .HasColumnName("squad_id");

                            b1.Property<int>("CurrentRating")
                                .HasColumnType("integer")
                                .HasColumnName("current_rating");

                            b1.Property<DateTime>("JoinedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("joined_at");

                            b1.HasKey("UserId", "SquadId");

                            b1.HasIndex("SquadId");

                            b1.ToTable("squad_memberships", (string)null);

                            b1.HasOne("PitchMate.Domain.Entities.Squad", null)
                                .WithMany()
                                .HasForeignKey("SquadId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("SquadMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
