import { describe, expect, it } from 'vitest';
import fc from 'fast-check';

import {
  INVITE_STATE_CODES,
  MEMBERSHIP_STATE_CODES,
  MEMBER_ROLE_CODES,
  REDEEM_OUTCOME_CODES,
  SKILL_TIER_CODES,
  SQUAD_FEATURE_CODES,
  codeFromInviteState,
  codeFromMemberRole,
  codeFromMembershipState,
  codeFromRedeemOutcome,
  codeFromSkillTier,
  codeFromSquadFeature,
  inviteStateFromCode,
  memberRoleFromCode,
  membershipStateFromCode,
  namedFromCode,
  redeemOutcomeFromCode,
  skillTierFromCode,
  squadFeatureFromCode,
  type InviteStateValue,
  type MemberRole,
  type MembershipStateValue,
  type RedeemOutcomeValue,
  type SkillTierValue,
  type SquadFeatureValue,
} from './enumCodes';

/**
 * Property tests for the Enum_Code_Map, placed beside the module they cover as
 * the design's Testing Strategy asks and running well above the 100-iteration
 * floor (20.1).
 *
 * These carry **Property 37: The Enum_Code_Map round-trips every named value** —
 * for any named value of Member_Role, Membership_State, Feature_Flag, Skill_Tier,
 * Invite_State (and Redeem_Outcome, which the same map serves), mapping the value
 * to its code and back yields the same named value (16.7); and for any integer
 * outside a table's code set, that table's reader yields no named value (16.6).
 *
 * Two things about how this is written matter more than the run counts.
 *
 * First, the **codes are asserted literally against an oracle read from the
 * backend enums**, not derived from the module under test. A generated round trip
 * cannot catch a wrong code: `codeFrom…` is built by reversing the very table
 * `…FromCode` reads, so a table that named `1 → beginner` would round-trip
 * perfectly and still misread every wire body. The oracle below was transcribed
 * from `Domain/Squads/SquadRole.cs`, `MembershipState.cs`, `SquadFeature.cs`,
 * `InviteState.cs`, `Domain/Rating/SkillTier.cs`, and
 * `Application/Squads/UseCases/RedeemInviteResult.cs`, and it is the only place
 * here that repeats a numeric literal.
 *
 * Second, the out-of-range side is stated as an **equivalence over arbitrary
 * integers** — a reader is asked to agree with the oracle for every integer, not
 * merely to reject a hand-picked few. `SkillTier` code `3` and `RedeemOutcome`
 * code `3` are additionally generated by name, because those two backend enums
 * declare no explicit values and so start at `0`: a 1-based reading would name
 * `3` and shift every tier by one, and that is exactly the defect this file
 * exists to catch.
 */

// --- the oracle: codes transcribed from the backend enums --------------------

/** `Domain/Squads/SquadRole.cs` — explicit values, 1-based. */
const MEMBER_ROLE_ORACLE: readonly (readonly [number, MemberRole])[] = [
  [1, 'owner'],
  [2, 'admin'],
  [3, 'member'],
];

/** `Domain/Squads/MembershipState.cs` — explicit values, 1-based. */
const MEMBERSHIP_STATE_ORACLE: readonly (readonly [
  number,
  MembershipStateValue,
])[] = [
  [1, 'active'],
  [2, 'inactive'],
];

/** `Domain/Squads/SquadFeature.cs` — explicit value, 1-based, one member. */
const SQUAD_FEATURE_ORACLE: readonly (readonly [number, SquadFeatureValue])[] = [
  [1, 'live-match-tracking'],
];

/** `Domain/Squads/InviteState.cs` — explicit values, 1-based. */
const INVITE_STATE_ORACLE: readonly (readonly [number, InviteStateValue])[] = [
  [1, 'active'],
  [2, 'revoked'],
  [3, 'expired'],
];

/** `Domain/Rating/SkillTier.cs` — **no** explicit values, so 0-based. */
const SKILL_TIER_ORACLE: readonly (readonly [number, SkillTierValue])[] = [
  [0, 'beginner'],
  [1, 'average'],
  [2, 'strong'],
];

/** `RedeemInviteResult.cs` — **no** explicit values, so 0-based. */
const REDEEM_OUTCOME_ORACLE: readonly (readonly [
  number,
  RedeemOutcomeValue,
])[] = [
  [0, 'joined'],
  [1, 'reactivated'],
  [2, 'already-member'],
];

// --- generators: values that name nothing ------------------------------------

/**
 * Integers weighted towards the region where every table's boundary sits, so the
 * near misses the task names — `SkillTier` 3, role 0 and 4, state 3, invite 4,
 * feature 2 — are generated densely rather than left to chance, while arbitrary
 * integers still occur.
 */
const integerCodeArb: fc.Arbitrary<number> = fc.oneof(
  { weight: 6, arbitrary: fc.integer({ min: -2, max: 6 }) },
  { weight: 2, arbitrary: fc.integer({ min: -50, max: 50 }) },
  { weight: 2, arbitrary: fc.integer() },
  {
    weight: 2,
    arbitrary: fc.constantFrom(
      -0,
      0,
      1,
      2,
      3,
      4,
      -1,
      Number.MAX_SAFE_INTEGER,
      Number.MIN_SAFE_INTEGER,
      2 ** 53,
      -(2 ** 53),
    ),
  },
);

/**
 * Numbers that are not integers. No enum code is fractional, so each must name
 * nothing rather than being truncated towards a code that does exist — `0.5`
 * naming `beginner` would be a silent misread of a mistyped field.
 */
const nonIntegerNumberArb: fc.Arbitrary<number> = fc.oneof(
  {
    weight: 4,
    arbitrary: fc.constantFrom(
      0.5,
      -0.5,
      0.999_999_999,
      1.000_000_001,
      1.5,
      -1.5,
      2.5,
      2.999_999,
      3.5,
      Number.EPSILON,
      Number.MIN_VALUE,
      Number.NaN,
      Number.POSITIVE_INFINITY,
      Number.NEGATIVE_INFINITY,
    ),
  },
  {
    weight: 3,
    arbitrary: fc
      .double({ min: -8, max: 8, noNaN: true })
      .filter((value) => !Number.isInteger(value)),
  },
  {
    weight: 2,
    arbitrary: fc.double({ noNaN: true }).filter((value) => !Number.isInteger(value)),
  },
);

/**
 * Strings, including the digit strings a JSON body would carry if a code were
 * serialised as text. `'1'` is not the wire representation of an enum here, and
 * naming it would make a mistyped field parse successfully instead of failing the
 * body carrying it (16.6).
 */
const stringCodeArb: fc.Arbitrary<string> = fc.oneof(
  {
    weight: 5,
    arbitrary: fc.constantFrom(
      '',
      ' ',
      '0',
      '1',
      '2',
      '3',
      '01',
      '1.0',
      ' 1',
      '1 ',
      '+1',
      '-1',
      '1e0',
      '0x1',
      'owner',
      'Owner',
      'active',
      'beginner',
      'joined',
      'live-match-tracking',
      'toString',
      'constructor',
      '__proto__',
      'valueOf',
      'hasOwnProperty',
      'NaN',
      'Infinity',
      'null',
      'undefined',
    ),
  },
  { weight: 2, arbitrary: fc.string({ minLength: 0, maxLength: 24 }) },
  { weight: 1, arbitrary: fc.string({ unit: 'grapheme', maxLength: 12 }) },
);

/**
 * Values of every other type, including the wrapper shapes a coercing reader
 * would wrongly name: a boxed number, a one-element array holding a code, and an
 * object carrying it under a field name.
 */
const otherTypeArb: fc.Arbitrary<unknown> = fc.oneof(
  {
    weight: 5,
    arbitrary: fc.constantFrom<unknown>(
      undefined,
      null,
      true,
      false,
      [],
      [1],
      [[1]],
      {},
      { role: 1 },
      { code: 1 },
      { value: 1 },
      1n,
      0n,
      Symbol('1'),
      () => 1,
      new Map([[1, 'owner']]),
      new Set([1]),
      new Date(1),
      Object(1),
      Object.create(null),
      [Number.NaN],
    ),
  },
  { weight: 1, arbitrary: fc.boolean() },
  { weight: 1, arbitrary: fc.bigInt() },
  { weight: 1, arbitrary: fc.array(integerCodeArb, { maxLength: 3 }) },
  { weight: 1, arbitrary: fc.record({ code: integerCodeArb }) },
  {
    weight: 3,
    arbitrary: fc
      .anything({ maxDepth: 2, withBigInt: true, withMap: true, withSet: true })
      .filter((value) => typeof value !== 'number'),
  },
);

/** Anything at all, weighted so both a named and an unnamed answer occur often. */
const anyCandidateArb: fc.Arbitrary<unknown> = fc.oneof(
  { weight: 5, arbitrary: integerCodeArb },
  { weight: 3, arbitrary: nonIntegerNumberArb },
  { weight: 3, arbitrary: stringCodeArb },
  { weight: 4, arbitrary: otherTypeArb },
);

/** Wraps `leaf` in `depth` levels of arrays and objects, alternating. */
function nest(leaf: unknown, depth: number): unknown {
  let value: unknown = leaf;

  for (let level = 0; level < depth; level += 1) {
    value = level % 2 === 0 ? [value] : { code: value };
  }

  return value;
}

// --- the shared table suite --------------------------------------------------

/**
 * The whole of Property 37 for one wire enum, run once per table with concrete
 * types so no cast is needed to hold the six tables in one place.
 *
 * @param label the wire enum's name, for the test titles
 * @param table the module's code table
 * @param fromCode the module's reader for that table
 * @param codeFrom the module's reverse reader for that table
 * @param oracle the codes transcribed from the backend enum
 * @param namedNearMisses codes the task names explicitly as naming nothing
 */
function describeCodeTable<TNamed extends string>(
  label: string,
  table: Readonly<Record<number, TNamed>>,
  fromCode: (code: unknown) => TNamed | undefined,
  codeFrom: (named: TNamed) => number,
  oracle: readonly (readonly [number, TNamed])[],
  namedNearMisses: readonly number[],
): void {
  const oracleByCode = new Map<number, TNamed>(
    oracle.map(([code, named]) => [code, named]),
  );
  const namedArb = fc.constantFrom(...oracle.map(([, named]) => named));
  const inRangeCodeArb = fc.constantFrom(...oracle.map(([code]) => code));

  // Feature: web-squads-screens, Property 37: The Enum_Code_Map round-trips every named value
  // Validates: Requirements 16.6, 16.7, 20.3
  describe(`Enum_Code_Map — ${label}`, () => {
    it('carries exactly the codes the backend enum declares', () => {
      // Asserted literally, because a generated round trip is blind to a wrong
      // code: the reverse direction is derived from this same table, so a shifted
      // table round-trips and still misreads every body (16.6).
      expect(
        Object.entries(table)
          .map(([code, named]) => [Number(code), named])
          .sort((left, right) => Number(left[0]) - Number(right[0])),
      ).toEqual(
        oracle
          .map(([code, named]) => [code, named])
          .sort((left, right) => Number(left[0]) - Number(right[0])),
      );
    });

    it('round-trips every named value through its code', () => {
      fc.assert(
        fc.property(namedArb, (named) => {
          // The property proper (16.7): named → code → named is the identity.
          const code = codeFrom(named);

          expect(Number.isInteger(code)).toBe(true);
          expect(fromCode(code)).toBe(named);
        }),
        { numRuns: 300 },
      );
    });

    it('round-trips every in-range code through its named value', () => {
      fc.assert(
        fc.property(inRangeCodeArb, (code) => {
          const named = fromCode(code);

          // The other direction of the same identity, which is what a parser
          // does: code in, name out, and the printer must put the same code back.
          expect(named).toBe(oracleByCode.get(code));
          expect(named).not.toBeUndefined();
          expect(codeFrom(named as TNamed)).toBe(code);
        }),
        { numRuns: 300 },
      );
    });

    it('names a code exactly when the backend enum declares it', () => {
      fc.assert(
        fc.property(integerCodeArb, (code) => {
          // Stated as an equivalence over arbitrary integers rather than as a
          // rejection of chosen few, so a reader that named everything and one
          // that named nothing both fail here (16.6).
          expect(fromCode(code)).toBe(oracleByCode.get(code));
        }),
        { numRuns: 1000 },
      );
    });

    it('names none of the codes just outside its set', () => {
      fc.assert(
        fc.property(fc.constantFrom(...namedNearMisses), (code) => {
          // The near misses the task names: `SkillTier` 3, role 0 and 4, state 3,
          // invite 4, feature 2. Each is one place from a code that does exist,
          // which is where an off-by-one table shows.
          expect(oracleByCode.has(code)).toBe(false);
          expect(fromCode(code)).toBeUndefined();
        }),
        { numRuns: 200 },
      );
    });

    it('names no non-integer number, including NaN and either infinity', () => {
      fc.assert(
        fc.property(nonIntegerNumberArb, (code) => {
          expect(fromCode(code)).toBeUndefined();
        }),
        { numRuns: 500 },
      );
    });

    it('names no string, not even the digits of a code it carries', () => {
      fc.assert(
        fc.property(stringCodeArb, (code) => {
          expect(fromCode(code)).toBeUndefined();
        }),
        { numRuns: 500 },
      );
    });

    it('names no value of any other type, including null and undefined', () => {
      fc.assert(
        fc.property(otherTypeArb, (code) => {
          expect(fromCode(code)).toBeUndefined();
        }),
        { numRuns: 500 },
      );
    });

    it('yields a named value of the table or nothing, for any input at all', () => {
      const names = new Set<string>(Object.values(table));

      fc.assert(
        fc.property(anyCandidateArb, (code) => {
          // Totality (16.6): every input settles, nothing throws, and no answer
          // is invented that the table does not carry.
          const named = fromCode(code);

          if (named !== undefined) {
            expect(names.has(named)).toBe(true);
          }
        }),
        { numRuns: 1000 },
      );
    });

    it('is deterministic across repeated reads', () => {
      fc.assert(
        fc.property(anyCandidateArb, (code) => {
          expect(fromCode(code)).toBe(fromCode(code));
          expect(fromCode(code)).toBe(fromCode(code));
        }),
        { numRuns: 500 },
      );
    });

    it('names nothing inside a structure nested to 100 levels', () => {
      fc.assert(
        fc.property(
          fc.oneof(inRangeCodeArb, integerCodeArb, stringCodeArb),
          fc.integer({ min: 1, max: 100 }),
          (leaf, depth) => {
            expect(fromCode(nest(leaf, depth))).toBeUndefined();
          },
        ),
        { numRuns: 300 },
      );
    });

    it('agrees with the shared reader over its own table', () => {
      fc.assert(
        fc.property(anyCandidateArb, (code) => {
          // Each `…FromCode` is a thin binding of `namedFromCode` to one table;
          // if one grew a rule of its own the two would part company here.
          expect(fromCode(code)).toBe(namedFromCode(table, code));
        }),
        { numRuns: 500 },
      );
    });

    it('names distinct values, so reversing the table loses nothing', () => {
      // The reverse map is keyed by name, so two codes sharing a name would drop
      // one code and break the round trip for it (16.7).
      const names = Object.values(table);

      expect(new Set(names).size).toBe(names.length);
      expect(names).toHaveLength(oracle.length);
    });
  });
}

describeCodeTable<MemberRole>(
  'Member_Role',
  MEMBER_ROLE_CODES,
  memberRoleFromCode,
  codeFromMemberRole,
  MEMBER_ROLE_ORACLE,
  [0, 4, -1, 5],
);

describeCodeTable<MembershipStateValue>(
  'Membership_State',
  MEMBERSHIP_STATE_CODES,
  membershipStateFromCode,
  codeFromMembershipState,
  MEMBERSHIP_STATE_ORACLE,
  [0, 3, -1, 4],
);

describeCodeTable<SquadFeatureValue>(
  'Feature_Flag',
  SQUAD_FEATURE_CODES,
  squadFeatureFromCode,
  codeFromSquadFeature,
  SQUAD_FEATURE_ORACLE,
  [0, 2, -1, 3],
);

describeCodeTable<InviteStateValue>(
  'Invite_State',
  INVITE_STATE_CODES,
  inviteStateFromCode,
  codeFromInviteState,
  INVITE_STATE_ORACLE,
  [0, 4, -1, 5],
);

describeCodeTable<SkillTierValue>(
  'Skill_Tier',
  SKILL_TIER_CODES,
  skillTierFromCode,
  codeFromSkillTier,
  SKILL_TIER_ORACLE,
  [3, 4, -1],
);

describeCodeTable<RedeemOutcomeValue>(
  'Redeem_Outcome',
  REDEEM_OUTCOME_CODES,
  redeemOutcomeFromCode,
  codeFromRedeemOutcome,
  REDEEM_OUTCOME_ORACLE,
  [3, 4, -1],
);

// --- the 0-based pair, stated on its own -------------------------------------

/**
 * `SkillTier` and `RedeemOutcome` declare no explicit values in the backend, so
 * they are 0-based while the other four are 1-based. The suite above would catch
 * a shift through its literal-code assertion, but the consequence is worth
 * stating in its own right: this is the single most plausible defect in the
 * module, and it is silent — every tier still reads as *a* tier, just the wrong
 * one.
 */
// Feature: web-squads-screens, Property 37: The Enum_Code_Map round-trips every named value
// Validates: Requirements 16.6, 16.7, 20.3
describe('Enum_Code_Map — the two 0-based enums are not read as 1-based', () => {
  it('names Skill_Tier 0, 1, and 2 and refuses 3', () => {
    expect(skillTierFromCode(0)).toBe('beginner');
    expect(skillTierFromCode(1)).toBe('average');
    expect(skillTierFromCode(2)).toBe('strong');
    // A 1-based table would name this, and the correct table must not.
    expect(skillTierFromCode(3)).toBeUndefined();
  });

  it('names Redeem_Outcome 0, 1, and 2 and refuses 3', () => {
    expect(redeemOutcomeFromCode(0)).toBe('joined');
    expect(redeemOutcomeFromCode(1)).toBe('reactivated');
    expect(redeemOutcomeFromCode(2)).toBe('already-member');
    expect(redeemOutcomeFromCode(3)).toBeUndefined();
  });

  it('reads negative zero as the code zero, where a table carries one', () => {
    fc.assert(
      fc.property(fc.constant(-0), (negativeZero) => {
        // A property read converts `-0` to the same key as `0`, and the two are
        // the same number, so the 0-based tables name it and the 1-based ones do
        // not — asserted so the behaviour is a decision rather than an accident.
        expect(skillTierFromCode(negativeZero)).toBe('beginner');
        expect(redeemOutcomeFromCode(negativeZero)).toBe('joined');
        expect(memberRoleFromCode(negativeZero)).toBeUndefined();
        expect(membershipStateFromCode(negativeZero)).toBeUndefined();
        expect(squadFeatureFromCode(negativeZero)).toBeUndefined();
        expect(inviteStateFromCode(negativeZero)).toBeUndefined();
      }),
      { numRuns: 100 },
    );
  });

  it('keeps the 1-based four away from code 0', () => {
    fc.assert(
      fc.property(fc.constant(0), (zero) => {
        expect(memberRoleFromCode(zero)).toBeUndefined();
        expect(membershipStateFromCode(zero)).toBeUndefined();
        expect(squadFeatureFromCode(zero)).toBeUndefined();
        expect(inviteStateFromCode(zero)).toBeUndefined();
      }),
      { numRuns: 100 },
    );
  });
});

// --- every reader at once ----------------------------------------------------

/**
 * The six readers paired with the oracle for the table each is meant to be bound
 * to, so totality and correct binding can be stated once over all of them.
 */
const READERS: readonly {
  readonly label: string;
  readonly read: (code: unknown) => string | undefined;
  readonly oracle: ReadonlyMap<number, string>;
}[] = [
  {
    label: 'Member_Role',
    read: memberRoleFromCode,
    oracle: new Map<number, string>(MEMBER_ROLE_ORACLE),
  },
  {
    label: 'Membership_State',
    read: membershipStateFromCode,
    oracle: new Map<number, string>(MEMBERSHIP_STATE_ORACLE),
  },
  {
    label: 'Feature_Flag',
    read: squadFeatureFromCode,
    oracle: new Map<number, string>(SQUAD_FEATURE_ORACLE),
  },
  {
    label: 'Invite_State',
    read: inviteStateFromCode,
    oracle: new Map<number, string>(INVITE_STATE_ORACLE),
  },
  {
    label: 'Skill_Tier',
    read: skillTierFromCode,
    oracle: new Map<number, string>(SKILL_TIER_ORACLE),
  },
  {
    label: 'Redeem_Outcome',
    read: redeemOutcomeFromCode,
    oracle: new Map<number, string>(REDEEM_OUTCOME_ORACLE),
  },
];

// Feature: web-squads-screens, Property 37: The Enum_Code_Map round-trips every named value
// Validates: Requirements 16.6, 16.7, 20.3
describe('Enum_Code_Map — every reader is total over every input', () => {
  it('yields a string or nothing for any value of any type, and throws nothing', () => {
    fc.assert(
      fc.property(anyCandidateArb, (code) => {
        for (const { read } of READERS) {
          const named = read(code);

          expect(named === undefined || typeof named === 'string').toBe(true);
        }
      }),
      { numRuns: 1000 },
    );
  });

  it('never converts a value, so a hostile toString or valueOf never runs', () => {
    fc.assert(
      fc.property(integerCodeArb, (code) => {
        let conversions = 0;
        const hostile = {
          valueOf() {
            conversions += 1;
            return code;
          },
          toString() {
            conversions += 1;
            return String(code);
          },
        };

        for (const { read } of READERS) {
          expect(read(hostile)).toBeUndefined();
        }

        expect(conversions).toBe(0);
      }),
      { numRuns: 300 },
    );
  });

  it('survives a self-referencing structure and a throwing accessor', () => {
    const selfReferencing: Record<string, unknown> = { code: 1 };
    selfReferencing.self = selfReferencing;

    const cyclicArray: unknown[] = [1];
    cyclicArray.push(cyclicArray);

    const throwingGetter = {
      get code(): number {
        throw new Error('must never be read');
      },
    };

    for (const { read } of READERS) {
      for (const candidate of [selfReferencing, cyclicArray, throwingGetter]) {
        expect(read(candidate)).toBeUndefined();
      }
    }
  });

  it('is bound to its own table, for every integer at once', () => {
    fc.assert(
      fc.property(integerCodeArb, (code) => {
        // Read side by side, because a reader bound to the wrong table — a real
        // possibility with six near-identical one-line bindings — answers
        // plausibly on its own and only looks wrong next to the others. The four
        // 1-based tables overlap on 1 and 2, so the names, not just the presence
        // of a name, are what separate them.
        const answers = READERS.map(({ label, read }) => [label, read(code)]);
        const expected = READERS.map(({ label, oracle }) => [
          label,
          oracle.get(code),
        ]);

        expect(answers).toEqual(expected);
      }),
      { numRuns: 1000 },
    );
  });
});
